### ISSUE TITLE
What would it take to support React 0.14??

### ISSUE THREAD

**Issue by kristianmandrup** [jscissr/react-polymer#1]
https://facebook.github.io/react/blog/2015/09/10/react-v0.14-rc1.html

Just curious... Would love to help making support for remaining core polymer elements ;)

**Comment by jscissr** [comment]
This module does a lot of monkey patching, and because react-dom is now a seperate package I guess some `require()`s have to be changed.

> In React DOM, arbitrary attributes are supported on custom elements (those with a hyphen in the tag name or an `is="..."` attribute).

This sounds like great news :sunglasses:, ...but it doesn't work as soon as you have [custom attributes on standard elements (`<div drawer></div>`)](https://elements.polymer-project.org/elements/paper-drawer-panel) :disappointed: .
The only advantage is that `reactPolymer.registerAttribute` needs only to be called for this case.

There are likely other internal changes in React which break react-polymer.
I didn't look into the code yet, I think I will when 0.14 is released. But of course you can already try yourself :smiley:

**Comment by jscissr** [comment]
I'm working on it. :)

**Comment by jscissr** [comment]
React 0.14 now supported!
